steps:
- id: 'branch_name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
     echo "$BRANCH_NAME"
     
- id: 'tf_init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
     terraform init

- id: 'tf_plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
     terraform plan

     


  
  

