timeout: 1200s
substitutions:
  _POLICY_REPO: '/workspace/policy-library' # add path to policies as per https://github.com/GoogleCloudPlatform/terraform-validator/blob/main/docs/policy_library.md
steps:
- id: 'setup'
  name: $_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY/terraform
  #entrypoint: /bin/sh
  entrypoint: /bin/bash    
  args:
  - -c
  - |
    tf_sa_email=${_TF_SA_EMAIL}
    if [[ -n ${tf_sa_email} ]]; then
      echo "Setting up gcloud for impersonation"
      gcloud config set auth/impersonate_service_account $tf_sa_email
    fi

    echo "Adding bucket information to backends"
    for i in `find -name 'backend.tf'`; do sed -i 's/UPDATE_ME/${_STATE_BUCKET_NAME}/' $i; done

# [START tf-plan_validate_all]
- id: 'tf plan validate all'
  name: work_bench_instance/$PROJECT_ID/$_GAR_REPOSITORY/terraform
  #entrypoint: /bin/bash
  entrypoint: /bin/sh
  args:
  - -c
  - |
      ./tf-wrapper.sh plan_validate_all ${BRANCH_NAME} ${_POLICY_REPO} ${PROJECT_ID} CLOUDSOURCE

artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/plan/${BUILD_ID}'
    paths: ['cloudbuild.yaml', 'work_bench_instance']
