steps:
  # Step 1: Check out the source code from the repository.
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '', '.']
  
  # Step 2: Initialize Terraform.
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']

  # Step 3: Run Terraform plan.
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['plan']

