steps:
  # Step 1: Check out the source code from the repository.
  - name: 'work_bench_instance'
    args: ['clone', 'https://github.com/Anilbelgod/practice_module.git']
  
  # Step 2: Initialize Terraform.
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']

  # Step 3: Run Terraform plan.
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['plan']

