

# [START tf-plan_validate_all]
- id: 'tf plan validate all'
  name: work_bench_instance/$PROJECT_ID/$_GAR_REPOSITORY/terraform
  #entrypoint: /bin/bash
  entrypoint: /bin/sh
  args:
  - -c
  - |
      ./tf-wrapper.sh plan_validate_all ${BRANCH_NAME} ${_POLICY_REPO} ${PROJECT_ID} CLOUDSOURCE

artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/plan/${BUILD_ID}'
    paths: ['cloudbuild.yaml', 'work_bench_instance']
